### ISSUE TITLE
Add .env.example variables to next.config.js

### ISSUE THREAD

**Issue by shikhar13012001** [shikhar13012001/blog-project#1]
We need to place the .env.example variables to `next.config.js` 
 for example
``` js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
... OtherConfig,
  // env
  env: {
    GITHUB_API_GRAPHQL_KEY: process.env.GITHUB_API_GRAPHQL_KEY,
   ....Other Variables
  },
};

module.exports = nextConfig;
```

**Comment by varunKT001** [comment]
@shikhar13012001 I would love to work on this issue. Please assign it to me.

**Comment by shikhar13012001** [comment]
Sure @varunKT001 , go a head, make sure to contributing guide before proceeding, should be trivial

**Comment by shikhar13012001** [comment]
Good work @varunKT001 please stay tuned for further issues.
